name: "Deploy to aws"

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: "Setup Node.js"
        uses: actions/setup-node@v4
        with:
          node-version: "21"

      - name: "Checkout code"
        uses: actions/checkout@v2

      - name: "Install dependencies"
        run: npm install

      - name: "Install pm2 globally"
        run: npm install pm2 -g

      - name: "run the tests"
        run: npm tests

      - name: "deploy on aws"
        run : pm2 start src/index.js